[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Serve static HTML files directly
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/search.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/resources.html"
  status = 200

[[redirects]]
  from = "/post"
  to = "/post.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile.html"
  status = 200

# Handle SPA routing - this should be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200