[build]
  publish = "dist"
  command = "npm run build"

# Serve static HTML files directly
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/search"
  to = "/search.html"
  status = 200

[[redirects]]
  from = "/resources"
  to = "/resources.html"
  status = 200

[[redirects]]
  from = "/post"
  to = "/post.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile.html"
  status = 200

# Handle query parameters for post pages
[[redirects]]
  from = "/post.html"
  to = "/post.html"
  status = 200

# Handle query parameters for profile pages
[[redirects]]
  from = "/profile.html"
  to = "/profile.html"
  status = 200

# Default fallback to home page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404